settings:
  title: 'Discord Extreme List Status'
  url: 'https://delly-production.techdude.workers.dev' # used for Slack messages
  logo: main_logo_animated.gif # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: discordextremelist-xyz # unique identifier
    name: Discord Extreme List (Main Site)
    description: 'The main site' # default=empty
    url: 'https://discordextremelist.xyz/en-US/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=

  - id: api.discordextremelist.xyz
    name: Discord Extreme List API
    description: 'API for the site'
    url: 'https://api.discordextremelist.xyz/health'
    method: GET
    expectStatus: 200

  - id: discordextremelist-gay
    name: Discord Extreme List (LGBTQ Site)
    description: 'LGBTQ extension of the main site'
    url: 'https://discordextremelist.gay/en-US/'
    method: GET
    expectStatus: 200
