settings:
  title: 'Techys Status Page'
  url: 'https://delly.techy-dev.workers.dev' # used for Slack messages
  logo: 3d_chicken.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
 - id: emojifierbot-com # unique identifier
    name: Emojifier Bot
    description: 'The main site' # default=empty
    url: 'https://emojifierbot.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=
    
 - id: docs-emojifierbot-com # unique identifier
    name: Emojifier Docs
    description: 'The documentation site' # default=empty
    url: 'https://docs.emojifierbot.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=
    
 - id: status-emojifierbot-com # unique identifier
    name: Emojifier Status
    description: 'The status page' # default=empty
    url: 'https://status.emojifierbot.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=
    
 - id: blog-emojifierbot-com # unique identifier
    name: Emojifier Blog
    description: 'The blog' # default=empty
    url: 'https://blog.emojifierbot.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=
    
 - id: status-emojifierbot-com # unique identifier
    name: Emojifier Status
    description: 'The bot status' # default=empty
    url: 'https://stats.emojifierbot.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=

  - id: emojifier-js-org
    name: Emojifier Bot
    description: 'The documentation site'
    url: https://emojifier.js.org'
    method: GET
    expectStatus: 200
    
  - id: discordextremelist-xyz # unique identifier
    name: Discord Extreme List (Main Site)
    description: 'The main site' # default=empty
    url: 'https://discordextremelist.xyz/en-US/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=

  - id: api.discordextremelist.xyz
    name: Discord Extreme List API
    description: 'API for the site'
    url: 'https://api.discordextremelist.xyz/health'
    method: GET
    expectStatus: 200

  - id: discordextremelist-gay
    name: Discord Extreme List (LGBTQ Site)
    description: 'LGBTQ extension of the main site'
    url: 'https://discordextremelist.gay/en-US/'
    method: GET
    expectStatus: 200
